# Exercise 1.A NumPy: Manipulating Arrays

This notebook covers NumPy array manipulation including looping, joining, stacking,
splitting, searching, sorting, and filtering arrays.

**Author:** Kidus  
**Course:** Year Up United Data Analytics  
**Week:** 7

In [2]:
# Import NumPy
import numpy as np

## Looping Through Arrays

In [3]:
# Create arrA as a 2D array
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [4]:
# Loop through the FIRST dimension of arrA and print each element * 2
# This loops over each ROW (returns full rows)
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
# Loop through the SECOND dimension of arrA and print each element * 2
# This loops over each individual VALUE inside each row
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


### Difference between the two loops

The **first loop** (`for x in arrA`) iterates over the **rows** of the 2D array.
Each `x` is a full row (a 1D array), so multiplying by 2 doubles every number in that row at once.

The **second loop** (`for y in x`) goes one level deeper and iterates over each **individual value**
inside every row. So instead of printing whole rows, it prints each single number multiplied by 2,
one at a time.

In [6]:
# Loop through second dimension, assign x*2 to loop_result
for x in arrA:
    for y in x:
        loop_result = x * 2

print(loop_result)

# loop_result stores x*2 (the whole row doubled), NOT y*2 (a single value)
# Even though we are in the inner loop (iterating over y), we assigned x*2
# So loop_result ends up being the LAST row of arrA multiplied by 2: [28, 30, 32]

[28 30 32]


## Joining and Stacking Arrays

In [7]:
# Concatenate arrA with arrA on axis=0 (default - stacks rows on top of each other)
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [8]:
# Concatenate arrA with arrA on axis=1 (joins columns side by side)
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [9]:
# Stack joined_array_1 with itself on default axis
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [10]:
# Try to stack joined_array_1 with joined_array_2 — this will error!
try:
    stacked_array_2 = np.stack((joined_array_1, joined_array_2))
except ValueError as e:
    print(f"Error: {e}")

# Error: all input arrays must have the same shape
# joined_array_1 has shape (4, 3) and joined_array_2 has shape (2, 6)
# np.stack() requires ALL arrays to have the EXACT same shape

Error: all input arrays must have the same shape


In [11]:
# Concatenate joined_array_1 with arrA on default axis=0
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [12]:
# Try to concatenate joined_array_1 with arrA on axis=1 — this will error!
try:
    another_2 = np.concatenate((joined_array_1, arrA), axis=1)
except ValueError as e:
    print(f"Error: {e}")

# Error: all arrays must have the same number of rows to join side by side on axis=1
# joined_array_1 has 4 rows but arrA only has 2 rows
# You can't attach columns if the row counts don't match

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2


In [13]:
# hstack, vstack, dstack

hstacked = np.hstack((arrA, arrA))
print("hstack:", hstacked)
# hstack (horizontal stack): joins arrays SIDE BY SIDE, expanding columns (axis=1)

vstacked = np.vstack((arrA, arrA))
print("vstack:", vstacked)
# vstack (vertical stack): stacks arrays ON TOP of each other, expanding rows (axis=0)

dstacked = np.dstack((arrA, arrA))
print("dstack:", dstacked)
# dstack (depth stack): stacks arrays ALONG THE THIRD DIMENSION, creating a 3D array

hstack: [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
vstack: [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
dstack: [[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [14]:
# Split joined_array_1 into 2
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# Result: 2 arrays, each 2-dimensional (2 rows x 3 columns)
# np.array_split divides the 4-row array into two equal halves

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [15]:
# Split joined_array_1 into 3
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# Result: 3 arrays, each 2-dimensional
# Since 4 rows can't split evenly into 3, NumPy gives us: (2 rows), (1 row), (1 row)
# NumPy handles uneven splits gracefully without throwing an error

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [16]:
# Use np.where() to find even numbers in arrA
# If even (num % 2 == 0): return the value from arrA
# If odd: return the string 'odd'
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [17]:
# Create arrB and sort it
arrB = np.array([(7, 6), (13, 5), (7, 3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)
# np.sort() sorts each ROW independently in ascending order

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [18]:
# Filter arrB for values LESS THAN 7
print(arrB)

z = arrB < 7          # boolean condition: True where value < 7
arrC = arrB[z]        # use boolean mask to filter — returns only matching values
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [19]:
# Filter arrB for values GREATER THAN OR EQUAL TO 7
y = arrB >= 7         # boolean condition: True where value >= 7
arrD = arrB[y]        # filter using boolean mask
print(arrD)

[ 7 13  7]
